Add second SMS
wrwrabbit/Partisan-Telegram-Android pull request #26
Opened 2021-02-06 14:39 UTC by ivanovivan12589

Close #10. 
Need a review to understand if I did it right.

2021-02-06 17:29 UTC, wrwrabbit commented
LGTM!
@vivabelarus what do you think?

@ivanovivan12589 the only thing I would add is migration of the old setting to the new ones (e.g. taking the old SMS settings of a user and putting in in the new trusted contact SMS settings)

2021-02-06 18:04 UTC, ivanovivan12589 commented
@wrwrabbit sounds good. I will do it as soon as I can.

2021-02-08 10:58 UTC, vivabelarus commented
Надеюсь, вы не возражаете, если я буду писать по-русски. Понятно же, что все мы русскоязычные.

Я сейчас занимаюсь разработкой версии с несколькими паролями и с несколькими действиями на каждый пароль. Думаю, такой подход будет более правильным. Но разработка может затянуться, поэтому пока что можно использовать эти исправления в качестве временной меры.

В коде есть одна проблема. Каждую отправку сообщения нужно обернуть в свой try-catch. В таком случае, если не получится отправить первое сообщение, можно попытаться отправить второе. А ошибка при отправке будет, если пользователь не заполнить номер телефона.

2021-02-08 10:59 UTC, vivabelarus requested changes

2021-02-08 10:59 UTC, vivabelarus commented on TMessagesProj/src/main/java/org/telegram/ui/Components/PasscodeView.java
> +                        manager.sendTextMessage(SharedConfig.sosFamilyPhoneNumber, null, SharedConfig.sosFamilyMessage, null, null);
Each sendTextMessage should be in a separate try-catch.

2021-02-08 10:59 UTC, vivabelarus commented on TMessagesProj/src/main/java/org/telegram/ui/Components/PasscodeView.java
> +                        manager.sendTextMessage(SharedConfig.sosTrustedContactPhoneNumber, null, SharedConfig.sosTrustedContactMessage, null, null);
Each sendTextMessage should be in a separate try-catch.

2021-02-08 11:10 UTC, ivanovivan12589 commented on TMessagesProj/src/main/java/org/telegram/ui/Components/PasscodeView.java
> +                        manager.sendTextMessage(SharedConfig.sosFamilyPhoneNumber, null, SharedConfig.sosFamilyMessage, null, null);
В последнем коммите я вместо `try-catch` оставил проверки на пустоту номера телефона и сообщения, которые напрямую вызывают ошибки в `sendTextMessage`. Или там может ещё что-то другое возникнуть? 
Если недостаточно `if`-ов, то добавлю `try-catch`.

2021-02-09 15:37 UTC, vivabelarus commented on TMessagesProj/src/main/java/org/telegram/ui/Components/PasscodeView.java
> +                        manager.sendTextMessage(SharedConfig.sosFamilyPhoneNumber, null, SharedConfig.sosFamilyMessage, null, null);
Да, не заметил сразу эти проверки. Должно быть достаточно.

2021-02-09 15:38 UTC, vivabelarus approved these changes

2021-02-09 15:38 UTC, merged