Multipasscode
wrwrabbit/Partisan-Telegram-Android pull request #31
Opened 2021-02-11 00:07 UTC by vivabelarus

2021-02-11 10:27 UTC, wrwrabbit requested changes
LGTM
@vivabelarus давай сделаем allowScreenCapture = false?
посмотри https://github.com/wrwrabbit/Partisan-Telegram-Android/issues/29

2021-02-11 14:56 UTC, ivanovivan12589 commented on TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/SosMessageAction.java
> +        manager.sendTextMessage(phoneNumber, null, message, null, null);
Тут точно не стоит добавить проверки на пустоту телефона и сообщения?

2021-02-11 15:22 UTC, ivanovivan12589 commented
LGTM
@vivabelarus ещё, может, стоит перенести прошлый пароль, если он был установлен?

2021-02-11 19:51 UTC, vivabelarus commented
> 
> 
> LGTM
> @vivabelarus давай сделаем allowScreenCapture = false?
> посмотри #29

ну я бы это в отдельной ветке сделал. Это вообще реально на уровне приложения реализовать?



> 
> 
> LGTM
> @vivabelarus ещё, может, стоит перенести прошлый пароль, если он был установлен?

В каком смысле?

2021-02-11 19:52 UTC, vivabelarus commented on TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/SosMessageAction.java
> +        manager.sendTextMessage(phoneNumber, null, message, null, null);
Можно добавить. Но все execute и так обёрнуты в try-catch

2021-02-11 20:04 UTC, ivanovivan12589 commented on TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/SosMessageAction.java
> +        manager.sendTextMessage(phoneNumber, null, message, null, null);
Просто в случае, когда есть 2 набора (номер телефона, сообщение) и один из наборов пустой, то исключение будет вылетать очень часто. А так небольшой проверкой этого можно избежать. А, насколько я знаю, процесс прокидывания исключения достаточно тяжелая вещь.

2021-02-11 20:04 UTC, ivanovivan12589 commented
Когда я скомпилил у себя новую версию, то установленный раньше пароль пропал. 
Я имел в виду, что если этот пароль был выставлен раньше, то, может, добавить его как Fake Password 1.

2021-02-11 20:06 UTC, vivabelarus commented
А, точно. Я и хотел это сделать. Позже пофикшу

2021-02-11 20:09 UTC, ivanovivan12589 commented
Кстати, это часом не решение #29? Или там другое имеется в виду?
https://stackoverflow.com/questions/38404237/how-to-hide-views-in-android-when-android-app-is-backgrounded-not-to-stop-andro

2021-02-11 20:36 UTC, vivabelarus commented
Там предлагается выставить флаг FLAG_SECURE. Его описание:

Window flag: treat the content of the window as secure, preventing it from appearing in screenshots or from being viewed on non-secure displays. 

То есть, на сколько понимаю, ответ не про то. Хотя вопрос, вроде, про то.

2021-02-11 22:33 UTC, vivabelarus commented
> 
> 
> Кстати, это часом не решение #29? Или там другое имеется в виду?
> https://stackoverflow.com/questions/38404237/how-to-hide-views-in-android-when-android-app-is-backgrounded-not-to-stop-andro

Хотя да, оно. Ну @wrwrabbit и говорил, что в приложении уже есть такой функционал. Нужно его только включить по умолчанию

2021-02-11 23:14 UTC, wrwrabbit commented
> Хотя да, оно. Ну @wrwrabbit и говорил, что в приложении уже есть такой функционал. Нужно его только включить по умолчанию

Угу, фунционал уже есть, только сделать allowScreenCapture = false по умолчанию и все

2021-02-12 14:34 UTC, ivanovivan12589 commented
@vivabelarus если большая нагрузка, то я могу часть изменений, которые нужны, взять на себя

2021-02-12 14:42 UTC, wrwrabbit approved these changes

2021-02-12 14:43 UTC, merged

2021-02-12 14:44 UTC, ivanovivan12589 commented
Или так)