Warning dialog fork
wrwrabbit/Partisan-Telegram-Android pull request #480
Opened 2024-01-20 21:01 UTC by dfgdfkjxcvkxnvlk

2024-01-21 17:16 UTC, vivabelarus requested changes

2024-01-21 17:16 UTC, vivabelarus commented on TMessagesProj/src/main/java/org/telegram/messenger/SharedConfig.java
> +            confirmDangerousActions = preferences.getBoolean("IsConfirmDangerousAction", true);
По-моему, не из тех preferences достаётся. Это preferences для уведомлений. А основные выше здесь в коде

2024-01-21 17:16 UTC, vivabelarus commented on TMessagesProj/src/main/res/values/strings.xml
> +    <string name="ConfirmDangerousAction">Confirm dangerous action</string>
Эти строки ещё желательно перевести на русский, белорусский. В strings_ru.xml и strings_be.xml. Можно ещё на украинский, если есть такая возможность

2024-01-21 17:16 UTC, vivabelarus commented on TMessagesProj/src/main/java/org/telegram/ui/PartisanSettingsActivity.java
> +            }else if (position == verifiedRow) {
После закрывающейся фигурной скобки нужен пробел

2024-01-21 17:16 UTC, vivabelarus commented on TMessagesProj/src/main/java/org/telegram/ui/PartisanSettingsActivity.java
> +                    }else if (position == confirmDangerousActionRow) {
После закрывающейся фигурной скобки нужен пробел

2024-01-21 17:16 UTC, vivabelarus commented on TMessagesProj/src/main/java/org/telegram/ui/PartisanSettingsActivity.java
> +                    }else if (position == confirmDangerousActionDetailRow) {
После закрывающейся фигурной скобки нужен пробел

2024-01-21 17:16 UTC, vivabelarus commented on TMessagesProj/src/main/java/org/telegram/ui/Components/ChatActivityEnterView.java
> +    private void confirmDangerousActionDialog(Runnable positive, Runnable negative) {
Перед методом нужна пустая строка

2024-01-21 17:16 UTC, vivabelarus commented on TMessagesProj/src/main/java/org/telegram/ui/Components/ChatActivityEnterView.java
> +    }
После метода нужна пустая строка

2024-01-21 17:16 UTC, vivabelarus commented on TMessagesProj/src/main/java/org/telegram/ui/Components/ChatActivityEnterView.java
> +                        if(!isConfirmDialogAlreadyShown) {
После if нужен пробел

2024-01-21 17:16 UTC, vivabelarus commented on TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/RemoveAfterReadingMessages.java
> +            List<RemoveAsReadMessage> messagesToCheck = null;
В dev это исправление уже есть. Нужно откатить то, что здесь и забрать из dev

2024-02-05 14:04 UTC, dfgdfkjxcvkxnvlk commented
@vivabelarus  seems like PR is done

2024-02-08 12:06 UTC, dfgdfkjxcvkxnvlk commented
done

2024-02-08 16:21 UTC, vivabelarus approved these changes

2024-02-08 16:22 UTC, merged